<a href="https://colab.research.google.com/github/ariaji25/MultiLayer_Perceptro_Delta_Rule/blob/master/MultyLayerPerceptro_DeltaRule.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

x = np.array([
    [1, 0, 0, 0, 1, 0],   
    [0, 1, 1, 1, 1, 0],
    [0, 0, 1, 0, 0, 1],
    [0, 0, 1, 0, 1, 0],
    [0, 1, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 1],
    [0, 0, 1, 1, 0, 0],
    [0, 1, 0, 1, 0, 0],
    [1, 0, 0, 1, 0, 1],
    [0, 1, 1, 1, 1, 1]
])
# 1 = A, 0= B
clas = np.array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0])

Kode di atas berfungsi untuk menginisialisasi data berupa inputan "x" dan label classifikasi nya "clas"

In [0]:
import random
w = np.zeros(6)
for i in range(len(w)):
  w[i] = random.uniform(0, 0.8)
  
w1 = np.zeros(6)
for i in range(len(w1)):
  w1[i] =random.uniform(0, 0.8)

w2 = np.zeros(2)
for i in range(len(w2)):
  w2[i]= random.uniform(0, 0.8)

kode di atas berfungsi untuk menginisialisasi nilai weight untuk masing masing node. w untuk node 1 di hiden layer, w1 untuk node 2 di hiden layer, w2 untuk node ke output layer

In [0]:
def countYin(yin, win):
  result =0.0
  for i in range(len(yin)):
    result+= yin[i] * win[i]
  return (result)

def sumfunction(xin, w):
  result = 0.0
  for i in range(len(xin)):
    result+=xin[i]*w[i]
  return result

def activation(yin):
  if(yin<0.5):
    return 0
  else:
    return 1
  
def trainingModel(w,xin, t):
  a = countYin(xin, w)
  y = activation(a)
  d = t - y
  for i in range(len(w)):
    w[i] = w[i]+ (0.2 * xin[i] *d)
  return w
  

kode di atas merupakan daftar fungsi yang diperlukan untuk delta rule learning, "countYin" berfungsi untuk menghitung y_in pada rumus delta rule, fungsi "sumfunction" berfungsi untuk melakukan fungsi sum pada node/ perceptron, fungsi "activation" berfungsi untuk melakukan activation function pada node/perceptron, fungsi "trainingModel" berfungsi untuk melakukan  delta rule learning.

In [0]:
def train(w, x, clas):
  c = 0
  for inputX in x:
    w = trainingModel(w, inputX, clas[c])
    c+=1

Kode di atas merupakan sebuah fungsi berfungsi untuk menjalankan delta rule learning model untuk setiap inputan 

In [0]:

def learning(w,x,clas):
  c = 0
  train(w,x,clas)
  for inputX in x:
    rc = sumfunction(inputX, w)
    pr = activation(rc)
    error = clas[c] - pr
    if(error!=0):
      learning(w,x,clas)
    c+=1




Kode di atas merupakan sebuah fungsi untuk melakukan delta rule learning model untuk inputan dan weight sampai memenuhi error == 0

In [8]:
# learning for 2 hiden layer
learning(w,x,clas)
learning(w1,x,clas)
# learning for the last node
newx = []
newclas = []
c=0
for inputX in x:
  rc = sumfunction(inputX, w)
  pr = activation(rc)
  rc1 = sumfunction(inputX, w1)
  pr1 = activation(rc1)
  newx.append([pr,pr1])
  newclas.append(clas[c])
  c+=1
learning(w2,newx, newclas)

# result for w,w1,w2
w,w1,w2

(array([ 0.47486156,  0.14556559,  0.23493359, -0.83157605,  0.27078397,
         0.54133821]),
 array([ 0.70127513,  0.34204974,  0.54802019, -1.17704696,  0.16863751,
         0.42000858]),
 array([0.07866285, 0.67497602]))

kode di atas berfungsi untuk melakukan training pada setipa node pada struktur ANN Multi Layer Perceptron (Delta Rule)

In [11]:
print(x)
c = 0
def showClas(y):
  if(y==0):
    return "B"
  else:
    return "A"
  
for inputX in x:
#   doing sum and activ function for node1 in hiden layer
  rc = sumfunction(inputX, w)
  pr = activation(rc)
  
#   doing sum and activ function for node2 in hiden layer
  rc1 = sumfunction(inputX, w1)
  pr1 = activation(rc1)
  
#   doing sum and activ function for node to output layer
  sumres = sumfunction([pr,pr1], w2)
  pred = activation(sumres)
  error = pred - clas[c]
  print("Input = ", inputX)
  print("predict : ", showClas(pr))
  print("expected : ", showClas(clas[c]))
  print("error : ",error)
  c+=1
 

[[1 0 0 0 1 0]
 [0 1 1 1 1 0]
 [0 0 1 0 0 1]
 [0 0 1 0 1 0]
 [0 1 0 0 0 1]
 [1 0 1 0 1 1]
 [0 0 1 1 0 0]
 [0 1 0 1 0 0]
 [1 0 0 1 0 1]
 [0 1 1 1 1 1]]
Input =  [1 0 0 0 1 0]
predict :  A
expected :  A
error :  0
Input =  [0 1 1 1 1 0]
predict :  B
expected :  B
error :  0
Input =  [0 0 1 0 0 1]
predict :  A
expected :  A
error :  0
Input =  [0 0 1 0 1 0]
predict :  A
expected :  A
error :  0
Input =  [0 1 0 0 0 1]
predict :  A
expected :  A
error :  0
Input =  [1 0 1 0 1 1]
predict :  A
expected :  A
error :  0
Input =  [0 0 1 1 0 0]
predict :  B
expected :  B
error :  0
Input =  [0 1 0 1 0 0]
predict :  B
expected :  B
error :  0
Input =  [1 0 0 1 0 1]
predict :  B
expected :  B
error :  0
Input =  [0 1 1 1 1 1]
predict :  B
expected :  B
error :  0


Kode di atas berfungsi untuk mencoba melakukan clasifikasi untuk setiap inputan